Repository AY2122S2-CS2103T-W12-4/tp, pull requests merged in 2022-04, with the labels that each got.

#205 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#206 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#211 Fix tables
  docs/UserGuide.md
Labels: type.Documentation, severity.VeryLow

#210 Update Meeting Time tests
  src/test/java/seedu/address/model/meeting/MeetingPlaceTest.java
  src/test/java/seedu/address/model/meeting/MeetingTimeTest.java
Labels: type.Test

#212 Fix v1.4 bugs
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/DeleteFieldCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/JobTitle.java
Labels: type.Bug, severity.Medium

#213 Update version
  src/main/java/seedu/address/MainApp.java
Labels: severity.VeryLow

#214 Fix Expired Meetings
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/meeting/MeetingTime.java
  src/test/java/seedu/address/model/meeting/MeetingTimeTest.java
Labels: type.Bug, priority.High, severity.High

#216 Improve UG clarity
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#215 Restrict meetings to existing contacts
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/meeting/MeetCommand.java
  src/main/java/seedu/address/logic/commands/meeting/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug

#125 Update tests for Find feature
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/person/FieldContainsKeywordsPredicateTest.java
Labels: type.Test

#221 Enhance tutorials
  docs/UserGuide.md
  docs/images/Tutorial/list_view.png
  docs/images/Tutorial/updated_meeting.png
Labels: type.Documentation, priority.High

#224 Update UI
  src/main/resources/view/ConfirmWindow.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ReacheTheme.css
Labels: type.Enhancement

#222 Add contributions to PPP
  docs/team/ckcherry23.md
Labels: type.Documentation, priority.High

#220 Add contributions to PPP
  docs/team/muraddurrani.md
Labels: type.Documentation

#226 Add introduction to DG and include acknowledgements
  docs/DeveloperGuide.md
Labels: type.Documentation

#228 Update description for ViewCommand in DG
  docs/DeveloperGuide.md
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/images/ViewCommandSequenceDiagram.png
Labels: type.Documentation

#225 Update parsing for meeting time
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/MeetingBook.java
  src/main/java/seedu/address/model/meeting/MeetingTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/meeting/JsonAdaptedMeeting.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: type.CodeQuality

#230 Fix PPP formatting
  docs/team/muraddurrani.md
Labels: type.Documentation

#233 Create utility methods for Meeting tests
  src/main/java/seedu/address/logic/commands/meeting/MeetCommand.java
  src/main/java/seedu/address/logic/commands/meeting/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/meeting/MeetCommandParser.java
  src/main/java/seedu/address/logic/parser/meeting/UpdateCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/EditMeetingDescriptorBuilder.java
Labels: type.Task, type.Test

#229 Improve code + Delete Fields tests
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/parser/DeleteFieldCommandParser.java
  src/main/java/seedu/address/model/person/EditPersonDescriptor.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/meeting/JsonAdaptedMeeting.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/ConfirmWindow.css
  src/main/resources/view/HelpWindow.css
  src/test/java/seedu/address/logic/commands/DeleteFieldCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteFieldCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug, priority.High, type.Test, type.CodeQuality

#237 Update DG with more details and relevance
  docs/DeveloperGuide.md
Labels: type.Documentation

#236 Update UI component in DG
  docs/DeveloperGuide.md
  docs/diagrams/ContactDetailsPageDiagram.puml
  docs/diagrams/HomePageDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/images/ContactDetailsPageDiagram.png
  docs/images/HomePageDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/ViewCommandSequenceDiagram.png
Labels: type.Documentation

#238 Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/meeting/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/meeting/JsonSerializableMeetingBook.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.High, severity.High

#241 Update UI theme
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/reache.png
  src/main/resources/view/ConfirmWindow.css
  src/main/resources/view/ConfirmWindow.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingListCard.fxml
  src/main/resources/view/ParticularsCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ReacheTheme.css
Labels: type.Task

#242 Add user stories for meetings
  docs/DeveloperGuide.md
Labels: type.Documentation

#234 update_command_tests
  src/main/java/seedu/address/logic/commands/meeting/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/meeting/UpdateCommandParser.java
  src/main/java/seedu/address/model/meeting/AgendaContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UpdateMeetingDescriptor.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/meeting/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/meeting/UpdateCommandParser.java
  src/test/java/seedu/address/logic/parser/meeting/UpdateCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
  src/test/java/seedu/address/testutil/UpdateMeetingDescriptorBuilder.java
Labels: type.Test

#243 Fix update meetings bug when meeting timing is same
  src/main/java/seedu/address/model/meeting/Agenda.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingPlace.java
  src/main/java/seedu/address/model/meeting/MeetingTime.java
Labels: type.Bug, priority.High, severity.Medium

#240 Update testing for Meet Command
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/meeting/MeetCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/meeting/MeetCommandTest.java
  src/test/java/seedu/address/logic/parser/meeting/MeetCommandParser.java
  src/test/java/seedu/address/logic/parser/meeting/MeetCommandParserTest.java
Labels: priority.High, type.Test

#247 Write tests for CancelCommandParser
  src/main/java/seedu/address/logic/parser/meeting/CancelCommandParser.java
  src/test/java/seedu/address/logic/parser/meeting/CancelCommandParser.java
  src/test/java/seedu/address/logic/parser/meeting/CancelCommandParserTest.java
Labels: type.Test

#248 Add tests for ViewCommand and ViewCommandParser
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: type.Test

#245 Add tests for UpdateMeetingDescriptor
  src/main/java/seedu/address/logic/commands/meeting/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/meeting/UpdateCommandParser.java
  src/main/java/seedu/address/model/meeting/UpdateMeetingDescriptor.java
  src/main/java/seedu/address/model/person/EditPersonDescriptor.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/meeting/EditMeetingDescriptorTest.java
  src/test/java/seedu/address/logic/commands/meeting/UpdateMeetingDescriptorTest.java
  src/test/java/seedu/address/testutil/UpdateMeetingDescriptorBuilder.java
Labels: type.Test

#250 Fix PPP
  docs/team/tonishka.md
Labels: type.Documentation

#235 Update docs
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/MeetingModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/MeetingModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Documentation, priority.High

#249 More tests
  src/main/java/seedu/address/logic/commands/meeting/CancelCommand.java
  src/test/java/seedu/address/logic/commands/meeting/CancelCommandtest.java
  src/test/java/seedu/address/model/id/IdTest.java
  src/test/java/seedu/address/model/meeting/MeetingListTest.java
Labels: type.Test

#254 Add tests for Pronoun
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PronounTest.java
Labels: type.Test

#251 Rename classes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/ContactDetailsPageParser.java
  src/main/java/seedu/address/logic/parser/HomePageParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/HomePageParserTest.java
Labels: type.CodeQuality

#256 more tests
  src/main/java/seedu/address/storage/meeting/JsonAdaptedAttendee.java
  src/main/java/seedu/address/storage/meeting/JsonAdaptedMeeting.java
  src/test/java/seedu/address/model/person/CompanyTest.java
  src/test/java/seedu/address/model/person/JobTitleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMeetingTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Test

#258 Add tests for ContactDetailsPageParser
  src/test/java/seedu/address/logic/parser/ContactDetailsPageParserTest.java
Labels: type.Test

#259 Update interface guide screenshots
  docs/UserGuide.md
  docs/images/ContactDetailsPage.png
  docs/images/ContactDetailsWindow.png
  docs/images/HomePage.png
  docs/images/MainWindow.png
Labels: type.Documentation

#260 Update occurrences of XXX window to XXX page
  docs/UserGuide.md
Labels: type.Documentation

#261 improve code quality
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/meeting/UpdateCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Test

#263 Update UI Screenshots in UG for Tutorials
  docs/UserGuide.md
  docs/images/Tutorial/Tutorial_2/cancel_birthday.png
  docs/images/Tutorial/Tutorial_2/list_view.png
  docs/images/Tutorial/Tutorial_2/new_meeting_created.png
  docs/images/Tutorial/Tutorial_2/updated_meeting.png
Labels: type.Documentation

#262 Update meeting DG
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/MeetCommandSequenceDiagram.puml
  docs/diagrams/UpdateCommandSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/MeetCommandSequenceDiagram.png
  docs/images/UpdateCommandSequenceDiagram.png
Labels: type.Documentation

#267 Update Model Class Diagram to show Labels
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Documentation

#264 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#265 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ClearActivityDiagram.puml
  docs/diagrams/ClearSequenceDiagram.puml
  docs/images/ClearActivityDiagram.png
  docs/images/ClearSequenceDiagram.png
  docs/images/testing/add_valid_number.png
  docs/images/testing/remove_attendees.png
Labels: type.Documentation

#271 Update_DG
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/EditCommandSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
Labels: type.Documentation

#269 Edit Interface Guide in UG
  docs/UserGuide.md
Labels: type.Documentation

#272 Update View Feature
  docs/DeveloperGuide.md
Labels: type.Documentation

#273 Update Edit Activity Daigram
  docs/diagrams/EditActivityDiagram.puml
  docs/images/EditActivityDiagram.png
Labels: type.Documentation

#274 Edit Implementation Sections in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#275 Update clear all data feature
  docs/DeveloperGuide.md
  docs/diagrams/ClearSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/MeetCommandSequenceDiagram.puml
  docs/diagrams/UpdateCommandSequenceDiagram.puml
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/images/ClearSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/MeetCommandSequenceDiagram.png
  docs/images/UpdateCommandSequenceDiagram.png
  docs/images/ViewCommandSequenceDiagram.png
  docs/team/ckcherry23.md
Labels: type.Documentation

#276 Add 'General Design Considerations' section
  docs/DeveloperGuide.md
Labels: type.Documentation

#277 Update outdated PPP extract
  docs/team/muraddurrani.md
Labels: type.Documentation

#279 Update manual testing steps
  docs/DeveloperGuide.md
  docs/team/ckcherry23.md
Labels: type.Documentation

#281 Add instructions for manual testing in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#284 Update to Result Display
  docs/DeveloperGuide.md
  docs/team/ckcherry23.md
Labels: type.Documentation

#283 Add list and view to manual testing
  docs/DeveloperGuide.md
Labels: type.Documentation
