Repository AY2122S2-CS2103T-W12-4/tp, pull requests merged in 2022-03, with the labels that each got.

#9 Update README for Reache
  README.md
  docs/images/Ui.png
Labels: type.documentation

#10 Update command and contact fields summary
  docs/UserGuide.md
Labels: type.documentation

#8 Update AboutUs page
  docs/AboutUs.md
  docs/images/ckcherry23.png
  docs/team/ckcherry23.md
Labels: type.documentation

#14 Update AboutUs
  docs/AboutUs.md
  docs/images/tonishka.png
Labels: type.documentation

#12 Update AboutUs page
  docs/AboutUs.md
  docs/images/muraddurrani.png
  docs/team/johndoe.md
  docs/team/muraddurrani.md
Labels: type.documentation

#16 Add sections 2.1 and 2.2 to UG
  docs/UserGuide.md
Labels: type.documentation

#17 Add user stories to DG for v1.2
  docs/DeveloperGuide.md
Labels: type.documentation

#20 Finished up with User Guide
  docs/UserGuide.md
Labels: type.documentation

#18 Add Use Case 1
  docs/DeveloperGuide.md
Labels: type.documentation

#21 Update DG with Product Scope, NFRs and Glossary
  docs/DeveloperGuide.md
  docs/images/Persona.png
Labels: type.documentation

#22 Update developer guide: Add Use Cases
  docs/DeveloperGuide.md
Labels: type.documentation

#25 Developer Guide: Standardised User Case Format
  docs/DeveloperGuide.md
Labels: enhancement

#36 Add navigation to user guide for help
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Story, priority.High

#44 Update tests
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/JobTitle.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAddress.java
  src/main/java/seedu/address/storage/JsonAdaptedEmail.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPhone.java
  src/main/java/seedu/address/storage/JsonAdaptedPronoun.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, type.Task

#48 Fix CI build tests
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/parser/ContactDetailsParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedAddress.java
  src/main/java/seedu/address/storage/JsonAdaptedEmail.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPhone.java
  src/main/java/seedu/address/storage/JsonAdaptedPronoun.java
  src/main/java/seedu/address/ui/AddressesCard.java
  src/main/java/seedu/address/ui/ContactDetailsPanel.java
  src/main/java/seedu/address/ui/EmailsCard.java
  src/main/java/seedu/address/ui/InfoBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NumbersCard.java
  src/main/java/seedu/address/ui/ParticularsCard.java
  src/main/resources/view/ContactDetailsPanel.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task

#34 Update DG for v1.2
  docs/DeveloperGuide.md
Labels: type.Documentation

#63 Change PersonCard and its FXML file to only display a person's name
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task

#65 Update UG for v1.2
  docs/UserGuide.md
Labels: type.Documentation

#60 Implement add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/ContactDetailsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#71 Implement view command
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
Labels: type.Task

#76 Add back command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/BackCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ContactDetailsParser.java
Labels: type.Task

#80 Make UI refresh to update a Person's information after they are edited
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug

#81 Update delete command for persons and fields
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ContactDetailsParser.java
  src/main/java/seedu/address/logic/parser/DeleteFieldCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Company.java
  src/main/java/seedu/address/model/person/EditPersonDescriptor.java
  src/main/java/seedu/address/model/person/JobTitle.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement, priority.High

#82 Add clear confirmation
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BackCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ConfirmCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/ConfirmWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ConfirmWindow.css
  src/main/resources/view/ConfirmWindow.fxml
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Enhancement, priority.Medium

#84 Add notes about command format
  docs/UserGuide.md
Labels: type.Documentation

#87 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Medium

#91 Update version in MainApp
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#93 Fix CI build tests
  docs/diagrams/DetailedParsingForEditSequenceDiagram.puml
Labels: type.Bug, severity.Low

#95 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Documentation

#97 Update DG for find feature
  build.gradle
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#100 Add view command implementation to DG
  docs/DeveloperGuide.md
  docs/diagrams/ViewCommandSequenceDiagram.puml
  docs/images/ViewCommandSequenceDiagram.png
Labels: type.Documentation, priority.High

#101 Update UG with new commands
  docs/UserGuide.md
Labels: type.Documentation

#104 Update DG for v1.3 draft
  docs/DeveloperGuide.md
Labels: type.Documentation

#96 Warn user about duplicate contacts
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/EditPersonDescriptor.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Story, priority.Medium

#107 Add skeletal code for meetings
  src/main/java/seedu/address/model/meeting/Agenda.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingPlace.java
  src/main/java/seedu/address/model/meeting/MeetingTime.java
  src/main/java/seedu/address/model/meeting/MeetingsList.java
  src/main/java/seedu/address/model/person/Name.java
Labels: type.Task, priority.High

#105 Update DG
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/plantuml/Find.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
Labels: type.Documentation, priority.High

#111 Update DG for v1.3
  docs/DeveloperGuide.md
  docs/diagrams/ClearActivityDiagram.puml
  docs/diagrams/ClearSequenceDiagram.puml
  docs/images/ClearActivityDiagram.png
  docs/images/ClearSequenceDiagram.png
Labels: type.Documentation

#110 Add default labels
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/LabelUtil.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteFieldCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/label/Label.java
  src/main/java/seedu/address/model/person/EditPersonDescriptor.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/AddressesCard.java
  src/main/java/seedu/address/ui/EmailsCard.java
  src/main/java/seedu/address/ui/NumbersCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement, type.Task, priority.High

#115 Simplify user feedback message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: severity.Medium

#117 Fix tests
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Bug

#116 Add meetings feature commands
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.High

#118 Parsers for meetings
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/meeting/CancelCommand.java
  src/main/java/seedu/address/logic/commands/meeting/EmptyCommand.java
  src/main/java/seedu/address/logic/commands/meeting/MeetCommand.java
  src/main/java/seedu/address/logic/commands/meeting/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/meeting/CancelCommandParser.java
  src/main/java/seedu/address/logic/parser/meeting/MeetCommandParser.java
  src/main/java/seedu/address/logic/parser/meeting/UpdateCommandParser.java
  src/main/java/seedu/address/model/MeetingBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyMeetingBook.java
  src/main/java/seedu/address/model/meeting/EditMeetingDescriptor.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingsList.java
  src/main/java/seedu/address/model/meeting/exceptions/DuplicateMeetingException.java
  src/main/java/seedu/address/model/meeting/exceptions/MeetingNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story

#120 Add Unique IDs for Person
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task, priority.High

#122 Update storage for meetings
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/logic/commands/meeting/MeetCommand.java
  src/main/java/seedu/address/logic/commands/meeting/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/meeting/MeetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingTime.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/meeting/JsonAdaptedAttendee.java
  src/main/java/seedu/address/storage/meeting/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/meeting/JsonMeetingBookStorage.java
  src/main/java/seedu/address/storage/meeting/JsonSerializableMeetingBook.java
  src/main/java/seedu/address/storage/meeting/MeetingBookStorage.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/MeetingBookBuilder.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: type.Story, type.Task, priority.High

#131 Set focus to command box after navigation
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: type.Enhancement, priority.Low

#135 Format date time in user-friendly manner
  src/main/java/seedu/address/model/meeting/MeetingTime.java
Labels: type.Enhancement, type.Task, severity.VeryLow, priority.Medium

#133 Fix bug in find command
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicate.java
Labels: type.Bug, priority.High, severity.High

#140 Implement Meetings UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/MeetingListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingListCard.fxml
  src/main/resources/view/MeetingListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task, priority.High

#145 Create panel for specific contacts that only shows their meetings
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/ui/ContactMeetingsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement, type.Task

#146 Update meetings feature in UG
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Documentation, priority.High

#150 Fix update success message
  src/main/java/seedu/address/logic/commands/meeting/UpdateCommand.java
Labels: severity.VeryLow

#154 Add Tutorials in UG
  docs/UserGuide.md
  docs/images/Tutorial/cancel_birthday.png
  docs/images/Tutorial/company_job_edited_screen.png
  docs/images/Tutorial/contact_details_page.png
  docs/images/Tutorial/email_edited_screen.png
  docs/images/Tutorial/main_window.png
  docs/images/Tutorial/new_meeting_created.png
  docs/images/Tutorial/sample_contacts_screen.png
  docs/images/Tutorial/tag_added.png
  src/main/java/seedu/address/logic/commands/meeting/UpdateCommand.java
  src/main/java/seedu/address/model/meeting/EditMeetingDescriptor.java
Labels: type.Documentation, priority.High

#155 Update UG for managing contacts
  docs/UserGuide.md
Labels: type.Documentation

#157 Show error if no fields provided for delete fields command
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
Labels: type.Bug

#158 Add notes for find command
  docs/UserGuide.md
Labels: type.Documentation

#159 Update name error message
  src/main/java/seedu/address/model/person/Name.java
Labels: type.Documentation
